#!/bin/sh

dockutil --no-restart --remove all

dockutil --no-restart --add "/Applications/1Password 7.app"
dockutil --no-restart --add "/Applications/Alfred 4.app"
dockutil --no-restart --add "/Applications/Backup and Sync.app"
dockutil --no-restart --add "/Applications/balenaEtcher.app"
dockutil --no-restart --add "/Applications/Cyberduck.app"
dockutil --no-restart --add "/Applications/Dash.app"
dockutil --no-restart --add "/Applications/Docker.app"
dockutil --no-restart --add "/Applications/Google Chrome.app"
dockutil --no-restart --add "/Applications/Hammerspoon.app"
dockutil --no-restart --add "/Applications/Insomnia.app"
dockutil --no-restart --add "/Applications/iTerm.app"
dockutil --no-restart --add "/Applications/Kaleidoscope.app"
dockutil --no-restart --add "/Applications/Keynote.app"
dockutil --no-restart --add "/Applications/Maccy.app"
dockutil --no-restart --add "/Applications/MacDown.app"
dockutil --no-restart --add "/Applications/Notion.app"
dockutil --no-restart --add "/Applications/Safari.app"
dockutil --no-restart --add "/Applications/Slack.app"
dockutil --no-restart --add "/Applications/Spotify.app"
dockutil --no-restart --add "/Applications/Suspicious Package.app"
dockutil --no-restart --add "/Applications/TeamViewer.app"
dockutil --no-restart --add "/Applications/Visual Studio Code.app"
dockutil --no-restart --add "/Applications/VLC.app"
dockutil --no-restart --add "/Applications/zoom.us.app"
dockutil --no-restart --add "/System/Applications/App Store.app"
dockutil --no-restart --add "/System/Applications/Automator.app"
dockutil --no-restart --add "/System/Applications/Calendar.app"
dockutil --no-restart --add "/System/Applications/Contacts.app"
dockutil --no-restart --add "/System/Applications/Home.app"
dockutil --no-restart --add "/System/Applications/Launchpad.app"
dockutil --no-restart --add "/System/Applications/Mail.app"
dockutil --no-restart --add "/System/Applications/Mission Control.app"
dockutil --no-restart --add "/System/Applications/Preview.app"
dockutil --no-restart --add "/System/Applications/Reminders.app"
dockutil --no-restart --add "/System/Applications/System Preferences.app"
dockutil --no-restart --add "/System/Applications/Utilities/Terminal.app"

killall Dock
